### ISSUE TITLE
Permission to bundle this example with the next release of SD-Updater

### ISSUE THREAD

**Issue by tobozo** [matsumo/m5stickc_tiny_menu#1]
Hey @matsumo, thanks again for your precious help with the sd-updater :+1: 

Since I can't copy your source (the Apache License you're using would require to re-license the whole repository and I'm lazy ^^), are you okay with me adding your project as a *submodule* in the examples folder of the M5Stack-SD-Updater repository ?

https://github.com/tobozo/M5Stack-SD-Updater/tree/unstable/examples

The main benefit of this is to have your M5stickC launcher available from the examples menu in the Arduino IDE, in a future release.

[edit]
also can you please mention @lovyan03's launcher and the M5Stack-SD-Updater in your Readme (required by the MIT License of the files you recycled) ?

**Comment by matsumo** [comment]
Of course, I changed license.
use to freely!

and sorry for missing credits.
Credits added.
